version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personality_prediction_app
    ports:
      - "8501:8501" 
      - "8000:8000" 

    networks:
      - app_network

networks:
  app_network: